// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoptFNZqAgZtpDuyJ8YklI8isSh1f8iKQ',
    appId: '1:833086409195:web:991dcc4a1447ec2a6ff1ae',
    messagingSenderId: '833086409195',
    projectId: 'cwyc-a859d',
    authDomain: 'cwyc-a859d.firebaseapp.com',
    storageBucket: 'cwyc-a859d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbktkCLFmHuJjhAW0SoGH725kzp76bNxY',
    appId: '1:833086409195:android:0ca0fb0597f454aa6ff1ae',
    messagingSenderId: '833086409195',
    projectId: 'cwyc-a859d',
    storageBucket: 'cwyc-a859d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOrFrDK8CyAxuF2578m_HUvt_WQp16KM',
    appId: '1:833086409195:ios:fc3337aef0b042556ff1ae',
    messagingSenderId: '833086409195',
    projectId: 'cwyc-a859d',
    storageBucket: 'cwyc-a859d.firebasestorage.app',
    iosBundleId: 'com.example.cwycs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtOrFrDK8CyAxuF2578m_HUvt_WQp16KM',
    appId: '1:833086409195:ios:fc3337aef0b042556ff1ae',
    messagingSenderId: '833086409195',
    projectId: 'cwyc-a859d',
    storageBucket: 'cwyc-a859d.firebasestorage.app',
    iosBundleId: 'com.example.cwycs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoptFNZqAgZtpDuyJ8YklI8isSh1f8iKQ',
    appId: '1:833086409195:web:d4a5924bff701def6ff1ae',
    messagingSenderId: '833086409195',
    projectId: 'cwyc-a859d',
    authDomain: 'cwyc-a859d.firebaseapp.com',
    storageBucket: 'cwyc-a859d.firebasestorage.app',
  );
}
